# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb28355224602fcdac5fb1b4170eb29b0a65aac1d55d9fa1b04cba962a8496b48d646995cab5850baba4192d54988422c86156bace1e04e7e788c58b8be419dc

test:
  secret_key_base: c08cc0b1df064ce80c486aa18359dd7f787c341a822902cdb086f441ea224fc82dbfce965ea87056c068150479419d6069273a0c1a20519e295384c3337bd021

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
